In [1]:
import pandas as pd
import numpy as np
import copy

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/machine-learning-course/syllabus/gh-pages/hiw-2019b/dataset-students-ml-2019b.csv')
df['nim'] = df['nim'].astype(str)

#encoding dof
dof_enc = {"dow_of_birth" : {"Monday":1, "Tuesday":2, "Wednesday":3, "Thursday":4, "Friday":5, "Saturday":6, "Sunday":7}}
df.replace(dof_enc, inplace=True)
df

,nim,gender,birth_city,birth_date,dow_of_birth,religion,height,weight,shoulder_width,shirt_height
0,1301174086,Male,Balikpapan,1998-09-09,3,Islam,179,67,51,68
1,1301174381,Male,Surabaya,1999-06-03,4,Islam,168,48,45,60
2,1301174065,Male,Bandung,1998-11-03,2,Islam,164,54,46,62
3,1301174440,Male,Bandung,1998-10-11,7,Islam,165,75,50,55
4,1301174263,Male,Batang,1999-11-18,4,islam,167,66,42,69
5,1301174113,Male,Pekanbaru,1999-06-21,1,Kristen,164,48,46,65
6,1301174294,Male,Jakarta,1999-07-14,3,Islam,175,65,47,70
7,1301170504,Male,Pontianak,2000-08-20,7,Islam,178,115,53,64
8,1301160503,Male,Blitar,1998-06-14,7,Islam,165,50,46,62
9,1301174313,Male,Singkawang,1999-03-14,7,Islam,178,73,50,60
10,1301174249,Male,Kijang,1999-02-03,3,islam,175,95,46,72
11,1301174542,Male,Bandung,1998-02-11,3,Islam,174,55,46,65
12,1301174029,Male,Denpasar,1999-03-18,4,Hindu,168,45,45,61
13,1301174046,Female,Medan,2001-04-21,6,Islam,163,53,42,61
14,1301170092,Female,Mataram,1999-03-29,1,Islam,165,52,45,60
15,1301174111,Female,Medan,1999-04-05,1,Kristen,159,53,40,53
16,1301174393,Female,Semarang,1999-01-14,4,Islam,153,50,43,60
17,1301174020,Female,Medan,1999-07-21,3,Kristen,160,58,44,67
18,1301174277,Male,Banjarbaru,1999-07-01,4,Islam,160,87,51,76
19,1301174300,Female,Purwakarta,1999-05-22,6,Islam,156,65,45,58
20,1301173180,Female,Denpasar,1999-06-17,4,Islam,150,41,37,58
21,1301174144,Male,Denpasar,1999-05-16,7,Hindu,175,80,48,76
22,1301174207,Male,Kutacane,1999-05-11,2,Islam,175,79,41,71
23,1301174227,Male,Bogor,1999-05-21,5,islam,166,57,46,70
24,1301174346,Male,Denpasar,1999-06-14,1,Hindu,177,69,48,62
25,1301174161,Male,Madiun,1999-08-14,6,Islam,168,74,52,71
26,1301174226,Female,Bandung,1997-11-26,3,Islam,158,60,44,60
27,1301174011,Male,Pangkalan Bun,1998-10-28,3,Islam,158,45,40,72
28,1301174130,Male,Banyuwangi,1998-12-22,2,islam,158,45,40,72
29,1301174401,Male,Solo,1999-08-02,1,Islam,167,60,46,64
...,...,...,...,...,...,...,...,...,...,...
36,1301174295,Male,Karawang,1998-10-26,1,Islam,179,90,55,77
37,1301170012,Male,Jakarta,1999-06-29,2,Islam,182,77,56,74
38,1301170066,Male,Bandung,1999-04-02,5,Islam,164,65,49,64
39,1301174228,Male,Yogyakarta,1999-05-05,3,Islam,165,80,48,65
40,1301174057,Female,Bandung,1998-05-14,4,Islam,160,62,52,58
41,1301174230,Female,Kendari,2000-04-12,3,islam,150,49,43,48
42,1301174021,Female,Jakarta,1999-10-04,1,islam,160,49,45,50
43,1301170505,Male,Jekardah,1999-09-15,3,Islam,172,63,57,76
44,1301174192,Male,Sibolga,1999-08-23,1,Islam,168,73,49,73
45,1301174145,Male,Jakarta,1999-02-28,7,Islam,160,65,50,58
46,1301174163,Male,Makassar,1999-10-02,6,Islam,168,65,50,68
47,1301170435,Female,Bekasi,1999-04-06,2,Islam,160,55,47,52
48,1301170278,Male,Banjarmasin,2000-06-16,5,Islam,175,58,46,71
49,1301174182,Female,Bekasi,1999-10-19,2,Islam,150,40,42,43
50,1301174250,Male,Bandung,1999-07-17,6,Islam,165,65,47,63
51,1301174597,Male,Pekalongan,1999-12-06,1,Islam,174,66,48,68
52,1301174314,Male,Depok,1999-10-06,3,Islam,170,60,45,68
53,1301170116,Male,Selong,1999-03-25,4,Islam,167,54,38,65
54,1301174052,Male,Cilacap,1999-04-26,1,Islam,168,55,42,67
55,1301172537,Female,Bandung,2000-04-13,4,Islam,158,58,41,46
56,1301170471,Male,Cirebon,1998-11-09,1,Islam,156,61,44,68
57,1301174112,Female,Medan,1999-11-29,1,Kristen,155,42,41,41
58,1301174093,Female,Gresik,2001-05-12,6,Islam,158,64,45,50
59,1301170301,Female,Bogor,1999-06-13,7,Islam,161,62,41,58
60,1301164134,Male,Tangerang,1998-12-15,2,Islam,177,60,50,70
61,1301174264,Male,Ampah,1998-12-16,3,Islam,175,90,49,72
62,1301164316,Male,Pati,1998-08-28,5,Islam,171,56,52,70
63,1301174131,Male,Pekanbaru,1998-08-19,3,Islam,168,65,50,73
64,1301170404,Male,Banda Aceh,1999-08-21,6,Islam,174,73,46,68
65,1301174030,Male,Banyumas,1999-02-10,3,Islam,175,79,53,70

In [3]:
#select features : dow_of_birth, height and weight
def getData(row):
    return [row['nim'],row['dow_of_birth'],row['height'],row['weight'],0,0]

In [4]:
X = df.apply(getData, axis=1).tolist()
X

[['1301174086', 3, 179, 67, 0, 0],
 ['1301174381', 4, 168, 48, 0, 0],
 ['1301174065', 2, 164, 54, 0, 0],
 ['1301174440', 7, 165, 75, 0, 0],
 ['1301174263', 4, 167, 66, 0, 0],
 ['1301174113', 1, 164, 48, 0, 0],
 ['1301174294', 3, 175, 65, 0, 0],
 ['1301170504', 7, 178, 115, 0, 0],
 ['1301160503', 7, 165, 50, 0, 0],
 ['1301174313', 7, 178, 73, 0, 0],
 ['1301174249', 3, 175, 95, 0, 0],
 ['1301174542', 3, 174, 55, 0, 0],
 ['1301174029', 4, 168, 45, 0, 0],
 ['1301174046', 6, 163, 53, 0, 0],
 ['1301170092', 1, 165, 52, 0, 0],
 ['1301174111', 1, 159, 53, 0, 0],
 ['1301174393', 4, 153, 50, 0, 0],
 ['1301174020', 3, 160, 58, 0, 0],
 ['1301174277', 4, 160, 87, 0, 0],
 ['1301174300', 6, 156, 65, 0, 0],
 ['1301173180', 4, 150, 41, 0, 0],
 ['1301174144', 7, 175, 80, 0, 0],
 ['1301174207', 2, 175, 79, 0, 0],
 ['1301174227', 5, 166, 57, 0, 0],
 ['1301174346', 1, 177, 69, 0, 0],
 ['1301174161', 6, 168, 74, 0, 0],
 ['1301174226', 3, 158, 60, 0, 0],
 ['1301174011', 3, 158, 45, 0, 0],
 ['1301174130', 2, 158, 45, 0, 0],
 ['1301174401', 1, 167, 60, 0, 0],
 ['1301170176', 5, 175, 63, 0, 0],
 ['1301170421', 2, 170, 56, 0, 0],
 ['1301174330', 6, 180, 67, 0, 0],
 ['1301174360', 7, 168, 54, 0, 0],
 ['1301170382', 6, 174, 68, 0, 0],
 ['1301174178', 1, 175, 85, 0, 0],
 ['1301174295', 1, 179, 90, 0, 0],
 ['1301170012', 2, 182, 77, 0, 0],
 ['1301170066', 5, 164, 65, 0, 0],
 ['1301174228', 3, 165, 80, 0, 0],
 ['1301174057', 4, 160, 62, 0, 0],
 ['1301174230', 3, 150, 49, 0, 0],
 ['1301174021', 1, 160, 49, 0, 0],
 ['1301170505', 3, 172, 63, 0, 0],
 ['1301174192', 1, 168, 73, 0, 0],
 ['1301174145', 7, 160, 65, 0, 0],
 ['1301174163', 6, 168, 65, 0, 0],
 ['1301170435', 2, 160, 55, 0, 0],
 ['1301170278', 5, 175, 58, 0, 0],
 ['1301174182', 2, 150, 40, 0, 0],
 ['1301174250', 6, 165, 65, 0, 0],
 ['1301174597', 1, 174, 66, 0, 0],
 ['1301174314', 3, 170, 60, 0, 0],
 ['1301170116', 4, 167, 54, 0, 0],
 ['1301174052', 1, 168, 55, 0, 0],
 ['1301172537', 4, 158, 58, 0, 0],
 ['1301170471', 1, 156, 61, 0, 0],
 ['1301174112', 1, 155, 42, 0, 0],
 ['1301174093', 6, 158, 64, 0, 0],
 ['1301170301', 7, 161, 62, 0, 0],
 ['1301164134', 2, 177, 60, 0, 0],
 ['1301174264', 3, 175, 90, 0, 0],
 ['1301164316', 5, 171, 56, 0, 0],
 ['1301174131', 3, 168, 65, 0, 0],
 ['1301170404', 6, 174, 73, 0, 0],
 ['1301174030', 3, 175, 79, 0, 0]]

In [5]:
#select k = 4
k = 4

#select random point as centroids
centroids = []
for i in range(k):
    rand = np.random.randint(0, len(X)-1)
    centroids.append(X[rand][1:4])

In [6]:
#calculate euclidian distance
def euclidian(u, v):
    return sum((p-q)**2 for p, q in zip(u, v))**0.5

In [19]:
flag = 0
#perform k-means algorithm until all centroid point has same value
while (True):
    cluster = []
    flag += 1
    
    for i in range(len(X)):
        euclid = []
        #calculate euclidian distance
        euclid.append(euclidian(X[i][1:],centroids[0]))
        euclid.append(euclidian(X[i][1:],centroids[1]))
        euclid.append(euclidian(X[i][1:],centroids[2]))
        euclid.append(euclidian(X[i][1:],centroids[3]))
        #select cluster from minimum euclidean
        idx = np.argmin(euclid)
        cluster.append(idx+1)
        #add cluster and euclidian distance to X
        X[i][4] = idx+1
        X[i][5] = euclid[idx]
        
    #clustering the centroids
    group = {}
    for j in set(cluster):
        group[j] = [i for i in range(len(cluster)) if cluster[i] == j]

    #store centroid information of each cluster
    dataX = {}
    for j in range(1,5):
        dataX[j] = [X[group[j][i]][1:4] for i in range(len(group[j]))]

    #assign new centroids to each cluster
    new_centroids = []
    new_centroids.append(np.mean(dataX[1], axis=0).tolist())
    new_centroids.append(np.mean(dataX[2], axis=0).tolist())
    new_centroids.append(np.mean(dataX[3], axis=0).tolist())
    new_centroids.append(np.mean(dataX[4], axis=0).tolist())
    
    if (centroids == new_centroids):
        break
    
    centroids = copy.copy(new_centroids)

In [20]:
print('Model Code: B')    
for i in range(len(X)):
    #print nim, cluster_number, euclidean distance to its centroid
    print('%s, %s, %0.4f' % (X[i][0], X[i][4], X[i][5]))

Model Code: B
1301174086, 2, 8.7540
1301174381, 3, 9.0215
1301174065, 1, 8.0223
1301174440, 4, 11.5507
1301174263, 2, 6.8705
1301174113, 3, 5.3404
1301174294, 2, 4.5002
1301170504, 4, 32.7268
1301160503, 3, 7.6716
1301174313, 4, 11.4583
1301174249, 4, 12.3963
1301174542, 2, 6.7903
1301174029, 3, 9.2944
1301174046, 3, 7.5490
1301170092, 3, 7.7923
1301174111, 3, 5.9878
1301174393, 3, 6.7122
1301174020, 1, 3.1282
1301174277, 4, 13.5985
1301174300, 1, 6.3302
1301173180, 3, 11.1110
1301174144, 4, 4.6414
1301174207, 4, 4.7479
1301174227, 1, 6.7665
1301174346, 2, 9.2409
1301174161, 4, 10.3098
1301174226, 1, 2.8909
1301174011, 3, 2.5665
1301174130, 3, 2.7301
1301174401, 2, 5.9693
1301170176, 2, 3.5002
1301170421, 2, 6.1345
1301174330, 2, 9.8544
1301174360, 2, 9.2872
1301170382, 2, 7.1657
1301174178, 4, 4.2033
1301174295, 4, 9.8510
1301170012, 4, 10.9393
1301170066, 1, 5.5613
1301174228, 4, 8.4731
1301174057, 1, 1.3363
1301174230, 3, 9.2188
1301174021, 3, 2.7178
1301170505, 2, 1.5779
1301174192, 4, 11.3707
1301174145, 1, 4.9929
1301174163, 2, 5.9813
1301170435, 1, 6.2621
1301170278, 2, 4.7423
1301174182, 3, 11.6984
1301174250, 1, 6.4310
1301174597, 2, 5.4480
1301174314, 2, 2.7193
1301170116, 2, 9.1529
1301174052, 2, 8.1541
1301172537, 1, 3.7129
1301170471, 1, 5.5613
1301174112, 3, 6.9800
1301174093, 1, 4.3507
1301170301, 1, 2.9641
1301164134, 2, 5.2702
1301174264, 4, 7.5361
1301164316, 2, 5.8403
1301174131, 2, 5.4698
1301170404, 4, 10.0831
1301174030, 4, 4.4349